sources:
  - !pw.io.fs.read
    path: conference_data.json
    format: json
    schema: 
      content: string
      metadata: string
      embedding: array<float>
    with_metadata: true

llm:
  !pw.xpacks.llm.llms.OpenAIChat
  model: "gpt-3.5-turbo"
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DefaultCache
  temperature: 0
  capacity: 8

embedder:
  !pw.xpacks.llm.embedders.OpenAIEmbedder
  model: "text-embedding-ada-002"
  cache_strategy: !pw.udfs.DefaultCache

splitter:
  !pw.xpacks.llm.splitters.TokenCountSplitter
  max_tokens: 400

parser:
  !pw.xpacks.llm.parsers.ParseUnstructured
  embedding_key: embedding
  metadata_keys:
    - conference
    - title
  content_key: content
  cache_strategy: !pw.udfs.DefaultCache

retriever_factory:
  !pw.stdlib.indexing.BruteForceKnnFactory
  reserved_space: 1000
  embedder: $embedder
  metric: !pw.stdlib.indexing.BruteForceKnnMetricKind.COS
  dimensions: 1536

document_store:
  !pw.xpacks.llm.document_store.DocumentStore
  docs: $sources
  parser: $parser
  splitter: $splitter
  retriever_factory: $retriever_factory

question_answerer:
  !pw.xpacks.llm.question_answering.BaseRAGQuestionAnswerer
  llm: $llm
  indexer: $document_store
  search_topk: 6  # Set the number of documents to retrieve

host: "0.0.0.0"
port: 8000

with_cache: true

terminate_on_error: false
